services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: personal-finance-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_finance
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - personal-finance-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # NestJS Application
  app:
    build: .
    container_name: personal-finance-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: personal_finance
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - personal-finance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/admin/test"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  personal-finance-network:
    driver: bridge
