# Development Docker Compose
services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: personal-finance-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personal_finance
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - personal-finance-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # NestJS Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: personal-finance-app-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: personal_finance
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - personal-finance-dev-network
    command: npm run start:dev

volumes:
  mysql_dev_data:

networks:
  personal-finance-dev-network:
    driver: bridge
